package com.collegeclubs.ecosystem_of_clubs.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.time.LocalDateTime;

@Document(collection = "Events")
public class Events {

    @Id
    private String id;  // Use MongoDB's autogenerated ID

    @NotNull(message = "Club ID cannot be null")
    private String clubId;

    @NotNull(message = "Event name cannot be null")
    private String eventName;

    private String eventType;  // Example: Workshop, Seminar, Hackathon, etc.

    @Size(max = 200, message = "Event description should not exceed 200 characters")
    private String eventDescription;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime startTime;

    @JsonFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss")
    private LocalDateTime endTime;

    // Default Constructor
    public Events() {
        // No need for UUID here as MongoDB ObjectId will handle it.
    }

    // Parameterized Constructor
    public Events(String clubId, String eventName, String eventType, String eventDescription, LocalDateTime startTime, LocalDateTime endTime) {
        this.clubId = clubId;
        this.eventName = eventName;
        this.eventType = eventType;
        this.eventDescription = eventDescription;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    // Getters and Setters
    public String getId() {
        return id; // MongoDB will auto-generate this ID
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getClubId() {
        return clubId;
    }

    public void setClubId(String clubId) {
        this.clubId = clubId;
    }

    public String getEventName() {
        return eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getEventDescription() {
        return eventDescription;
    }

    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }

    public LocalDateTime getStartTime() {
        return startTime;
    }

    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    public LocalDateTime getEndTime() {
        return endTime;
    }

    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }
}
